"use server";

import { inArray } from "drizzle-orm";
import { auth } from "@/app/lib/auth";
import { db } from "@/index";
import { user as userTable } from "@/db/schema";

export async function seedTestAccounts(_formData: FormData) {
  const ctx = await auth.$context;
  const seedIds: string[] = [];

  for (let i = 1; i <= 20; i++) {
    const id = `seed-user-${i}`;
    const email = `user${i}@test.local`;
    const password = "password123";
    seedIds.push(id);

    try {
      const user = await ctx.internalAdapter.createUser({
        id,
        name: `Test User ${i}`,
        email,
        emailVerified: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      });

      await ctx.internalAdapter.linkAccount({
        userId: user.id,
        providerId: "credential",
        accountId: user.id,
        password: await ctx.password.hash(password),
      });
    } catch {
      // Skip duplicates
    }
  }

  // Handles are auto-generated by the user-create hook, but land unconfirmed —
  // which would bounce every test login to /onboarding/handle. Test accounts
  // keep their generated handle, so mark them done. Runs over all seed ids so
  // re-seeding also repairs accounts created before this step existed.
  await db
    .update(userTable)
    .set({ handleConfirmed: true })
    .where(inArray(userTable.id, seedIds));
}
